"""empty message

Revision ID: 64016ee68b47
Revises: 7ae48df338d2
Create Date: 2023-04-12 16:00:27.711236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64016ee68b47'
down_revision = '7ae48df338d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
                              existing_type=sa.REAL(),
                              type_=sa.Float(precision=2),
                              existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
                              existing_type=sa.Float(precision=2),
                              type_=sa.REAL(),
                              existing_nullable=False)

    # ### end Alembic commands ###
