"""empty message

Revision ID: 845307433552
Revises: 1cf0c1580fed
Create Date: 2023-04-07 22:25:17.067850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845307433552'
down_revision = '1cf0c1580fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
